export const GET_PATIENTS_RESPONSE = 'GET_PATIENTS_RESPONSE'
export const GET_PATIENT_RESPONSE = 'GET_PATIENT_RESPONSE'
export const ADD_NEW_PATIENT_RESPONSE = 'ADD_NEW_PATIENT_RESPONSE'
export const UPDATE_EXISTING_PATIENT_RESPONSE = 'UPDATE_EXISTING_PATIENT_RESPONSE'
export const DELETE_PATIENT_RESPONSE = 'DELETE_Patient_RESPONSE'

export const API_CALL_BEGIN = 'API_CALL_BEGIN'
export const API_CALL_ERROR = 'API_CALL_ERROR'
